#!/bin/bash
#########################
# COMPILAR
#########################
if [ -f Main.c ]; then
    FILE=""
    for file in *.c
    do
    	base="${file%%.*}"
    	gcc -c $file '-I'"$PWD/src" -o obj/$base.o
    	FILE=obj/$base.o
    	break;
    done
    for i in {01..11}
    do
    	gcc -c src/main$i.c '-I'"$PWD/src" -o obj/main$i.o
    	gcc obj/main$i.o "$FILE" -o bin/p$i -lm
    done
else
    echo "Nenhum arquivo contendo o código fonte foi encontrado no diretório $PWD"
    exit
fi

#########################
# EXECUTAR TESTES
#########################
COUNTER=0
GRADE=0
mkdir test

for i in {01..11}
do
   let COUNTER=COUNTER+1
      touch ./test/$f
       ./src/gen-points.py > ./test/in$i.txt
       cat ./test/in$i.txt | bin/p$i > ./test/file$i
    DIFF=$(diff -w ./test/file$i ./out/file$i)
    if [ "$DIFF" == "" ]; then
        let GRADE=GRADE+1
  	    echo "$COUNTER ok"
    else
        echo "$COUNTER incorreto ($f)"
    fi
done

echo -n "Nota "
echo -n $(echo "scale=2; $GRADE*10/$COUNTER" | bc)
echo " ($GRADE de $COUNTER)"
